"""tutor schema: parents, learners, sessions, exercises, telemetry

Revision ID: 33eea98fba87
Revises: 
Create Date: 2026-08-29 12:55:55.371331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33eea98fba87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('learner_id', sa.String(length=32), nullable=True),
    sa.Column('task', sa.String(length=40), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_learner_id'), ['learner_id'], unique=False)

    op.create_table('parents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parents_clerk_user_id'), ['clerk_user_id'], unique=True)

    op.create_table('learners',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('school_class', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('avatar', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learners_parent_id'), ['parent_id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('learner_id', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=True),
    sa.Column('topic_id', sa.String(length=60), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_learner_id'), ['learner_id'], unique=False)

    op.create_table('safety_flags',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('learner_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safety_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_flags_learner_id'), ['learner_id'], unique=False)

    op.create_table('topic_mastery',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('learner_id', sa.String(length=32), nullable=False),
    sa.Column('topic_id', sa.String(length=60), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'topic_id', name='uq_mastery_learner_topic')
    )
    with op.batch_alter_table('topic_mastery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_mastery_learner_id'), ['learner_id'], unique=False)

    op.create_table('exercises',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('learner_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('topic_id', sa.String(length=60), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('accepted_variants', sa.JSON(), nullable=False),
    sa.Column('hints', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_learner_id'), ['learner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_topic_id'), ['topic_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intercepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_session_created', ['session_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_session_id'), ['session_id'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('exercise_id', sa.String(length=32), nullable=False),
    sa.Column('learner_id', sa.String(length=32), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('given', sa.Text(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('graded_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_learner_id'), ['learner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_learner_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_exercise_id'))

    op.drop_table('attempts')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_session_id'))
        batch_op.drop_index('ix_messages_session_created')

    op.drop_table('messages')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_topic_id'))
        batch_op.drop_index(batch_op.f('ix_exercises_learner_id'))

    op.drop_table('exercises')
    with op.batch_alter_table('topic_mastery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_mastery_learner_id'))

    op.drop_table('topic_mastery')
    with op.batch_alter_table('safety_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_flags_learner_id'))

    op.drop_table('safety_flags')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_learner_id'))

    op.drop_table('chat_sessions')
    with op.batch_alter_table('learners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learners_parent_id'))

    op.drop_table('learners')
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parents_clerk_user_id'))

    op.drop_table('parents')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_calls_learner_id'))

    op.drop_table('llm_calls')
    # ### end Alembic commands ###
