"""sheets: multi-blank exercises and a gated hint level

Revision ID: b5ad2ba8a5ef
Revises: 33eea98fba87
Create Date: 2026-08-29 13:53:12.249695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ad2ba8a5ef'
down_revision: Union[str, Sequence[str], None] = '33eea98fba87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blank_id', sa.String(length=8), nullable=False))

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sheet_id', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('kind', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('blanks', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('hint_level', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('solved', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_exercises_sheet_id'), ['sheet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_sheet_id'))
        batch_op.drop_column('solved')
        batch_op.drop_column('hint_level')
        batch_op.drop_column('blanks')
        batch_op.drop_column('position')
        batch_op.drop_column('kind')
        batch_op.drop_column('sheet_id')

    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_column('blank_id')

    # ### end Alembic commands ###
